### ISSUE TITLE
Complete FOSDEM slides with commands.

### ISSUE THREAD

**Issue by layus** [nbp/slides#1]
Would you mind adding to the FOSDEM/2015.Nix-NixOS-NixOps/ folder the commands you used for the live demo ?

The video of the presentation is not yet available, and I have some difficulties to reproduce the complex commands you used during the presentation.

Thanks !

PS: J'aurais pu le faire en français aussi, mais maintenant que j'ai tout écrit... :-)

**Comment by nbp** [comment]
The commands are in the notes of the presentation.  They might not work without creating another system-profile, but this is not mandatory as you canreplace the `nixos-rebuild` tool by `nix-build -A vm -f nixos/default.nix`
